### ISSUE TITLE
Investigate the use of gobot as an standalone library for Intel Edison

### ISSUE THREAD

**Issue by ericho** [ericho/iot_sensors#1]
Now gobot has support for Intel Edison, but at least in their examples the usage depends on a Run function. 

It would be great to use the library without the need of use all the gobot framework.

**Comment by ericho** [comment]
First experiment: 
The following code doesn't work: 

``` go
package main

import (
    "time"

    "github.com/hybridgroup/gobot/platforms/gpio"
    "github.com/hybridgroup/gobot/platforms/intel-iot/edison"
)

func main() {
    e := edison.NewEdisonAdaptor("edison")
    led := gpio.NewLedDriver(e, "led", "13")
    for {
        led.Toggle()
        time.Sleep(1)
    }
}
```

This was compiled with : 
`GOARCH=386 GOOS=linux go build blink.go`

And running the binary in the Edison I get the following error: 

```
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x8118760, 0x184581c0)
    /usr/local/go/src/runtime/panic.go:481 +0x326
github.com/hybridgroup/gobot/platforms/intel-iot/edison.(*EdisonAdaptor).digitalPin(0x184540c0, 0x8149724, 0x2, 0x8149b64, 0x3, 0x0, 0x0, 0x0, 0x0)
    /home/erich/src/go/src/github.com/hybridgroup/gobot/platforms/intel-iot/edison/edison_adaptor.go:308 +0x15c
github.com/hybridgroup/gobot/platforms/intel-iot/edison.(*EdisonAdaptor).DigitalWrite(0x184540c0, 0x8149724, 0x2, 0x1, 0x0, 0x0)
    /home/erich/src/go/src/github.com/hybridgroup/gobot/platforms/intel-iot/edison/edison_adaptor.go:395 +0x52
github.com/hybridgroup/gobot/platforms/gpio.(*LedDriver).On(0x184540f0, 0x0, 0x0)
    /home/erich/src/go/src/github.com/hybridgroup/gobot/platforms/gpio/led_driver.go:76 +0x5e
github.com/hybridgroup/gobot/platforms/gpio.(*LedDriver).Toggle(0x184540f0, 0x0, 0x0)
    /home/erich/src/go/src/github.com/hybridgroup/gobot/platforms/gpio/led_driver.go:97 +0x54
main.main()
    /home/erich/src/go/src/github.com/ericho/iot_sensors/go/blink.go:14 +0x90
```

Some setup is stil needed. 
i need to understand how the gobot.Start() function works to see if is possible to wire the missing parts. However if it's not possible is still possible to use a channel from the go routine and then communicate the data with the snap plugin.

**Comment by ericho** [comment]
I raise the following issue on gobot's github page 
https://github.com/hybridgroup/gobot/issues/302

**Comment by ericho** [comment]
This code works now

``` go
package main

import (
    "time"
    "github.com/hybridgroup/gobot/platforms/gpio"
    "github.com/hybridgroup/gobot/platforms/intel-iot/edison"
)

func main() {
    e := edison.NewEdisonAdaptor("edison")
    led := gpio.NewLedDriver(e, "led", "13")
    e.Connect()
    for {
        led.Toggle()
        time.Sleep(1000 * time.Millisecond)
    }
}
```

**Comment by ericho** [comment]
Now is possible also to read from an analog source, a lm35 driver was included in the repository. 
I'm closing this issue as we have now a way to get data from Edison using Go.
